### ISSUE TITLE
Item list overlapping other form fields

### ISSUE THREAD

**Issue by LordPacDemon** [QNimbus/node-red-contrib-openhab-v2#14]
Please see attached screenshot. The item searchbox and list are blocking access to the topic and payload fields. I am using node-red v1.0.1.

![image](https://user-images.githubusercontent.com/30553921/66254263-2dac4d00-e774-11e9-951d-5fcc150aea93.png)

Event types not possible to select, it has hals overlapping.

**Comment by michaelliebel** [comment]
Quick fix.
If you delete the "position: absolute;" in node-red-contrib-openhab-v2/static/css/bootstrap-multiselect.css it kind of works.
Looks like that css changed quite a bit in node-red 1.0.0 so this node needs some overhaul.

**Comment by LordPacDemon** [comment]
> Quick fix.
> If you delete the "position: absolute;" in node-red-contrib-openhab-v2/static/css/bootstrap-multiselect.css it kind of works.
> Looks like that css changed quite a bit in node-red 1.0.0 so this node needs some overhaul.

The small fix help.
Thank you.

**Comment by cybix32** [comment]
This have annoyed me for a while, great fix.
Thanks!
