### ISSUE TITLE
What's the differences of "ItemStateChanged" and "ItemState"?

### ISSUE THREAD

**Issue by kevinshane** [QNimbus/node-red-contrib-openhab-v2#9]
Hey guys, I can see the `ItemStateChanged` has `oldValue` rather than the `ItemState` event payload. But what else differences between these two?
Also, both types will output the payload **twice** which makes no sense if we can decide which event type in drop down menu.
Can I make the `ItemState` output only once with only the item state? and make the `ItemStateChanged` also ouput once but with more extra payload such as `oldValue`?
Thanks!

**Comment by kevinshane** [comment]
Yes Sir you are right, I did ticked on `Start output` and the issue happen. (send payload twice)
After I tick off the `Start output` everything become normal now.
Could you please fix that? Thank you so much!

**Comment by QNimbus** [comment]
Fix is already pushed to GitHub; should propagate to npmjs in a short while.

[Fixed in commit bf12d26f75e328e4aaa479745572cf3e5cf4ad73](https://github.com/QNimbus/node-red-contrib-openhab-v2/commit/bf12d26f75e328e4aaa479745572cf3e5cf4ad73#diff-e12e9ed880a24afdde46216a7a528920)

**Comment by kevinshane** [comment]
really awesome job! Thank you sir!
We can close the issue now.
